services:
  - type: web
    name: heard-app-beta
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
